Develop
edrickhoo/Google-Books-List pull request #1
Opened 2022-12-14 06:49 UTC by edrickhoo

2022-12-15 10:08 UTC, ABaulderstone requested changes

2022-12-15 10:08 UTC, ABaulderstone commented on src/App.tsx
> +  const [booksData, setBooksData] = useState<bookType[] | null>(null);
```ts
const [booksData, setBooksData] = useState<bookType[] >([]);
```
Empty array is still technically an array of `bookType`, which means no need for null check just a check on length of array

2022-12-15 10:08 UTC, ABaulderstone commented on src/App.tsx
> +  const [error, setError] = useState<string | null>(null);
Similarly 
```ts
const [error, setError] = useState<string>("");
```
Empty string is still a falsy value. No need for union type

2022-12-15 10:08 UTC, ABaulderstone commented on src/App.tsx
> +    } catch (err: any) {
err: Error should be fine here

2022-12-15 10:08 UTC, ABaulderstone commented on src/api/google-books-api.tsx
> +};
Generally prefer interfaces to types. Naming convention is similar to classes
```ts
export interface Book = {
  img: string;
  author: [];
  description: string;
  title: string;
  publishedDate: string;
  languages: string;
  rating: string;
  ratingCount: string;
  shortDescription: string;
  pageCount: string;
};
```

2022-12-15 10:08 UTC, ABaulderstone commented on src/components/Book/Book.tsx
> +          : `Author: ${author}`}
You can do this in your organiseData function

2022-12-15 10:08 UTC, ABaulderstone commented on src/container/Books-container/Books.tsx
> +          booksData.map((book: any, idx: number) => {
Can avoid the null check with the previous type change. 
`book: bookType` or better yet `book: Book`

2022-12-15 10:08 UTC, ABaulderstone commented on src/container/Books-container/Books.tsx
> +      ) : null}
```ts
 {moreInfo && moreInfoData && (
        <MoreInfo toggleMoreInfo={toggleMoreInfo} moreInfoData={moreInfoData} />
      )}
 ```
 You need the null check for moreInfoData to satisfy that the type you're passing into <MoreInfo> isn't null. No need for a ternary if you're just rendering null as the alternative

2022-12-16 02:44 UTC, edrickhoo commented on src/App.tsx
> +  const [booksData, setBooksData] = useState<bookType[] | null>(null);
Fixed

2022-12-16 02:45 UTC, edrickhoo commented on src/App.tsx
> +  const [error, setError] = useState<string | null>(null);
Fixed

2022-12-16 02:46 UTC, edrickhoo commented on src/api/google-books-api.tsx
> +};
Fixed

2022-12-16 02:46 UTC, edrickhoo commented on src/container/Books-container/Books.tsx
> +          booksData.map((book: any, idx: number) => {
Fixed

2022-12-16 02:47 UTC, edrickhoo commented on src/container/Books-container/Books.tsx
> +      ) : null}
Fixed

2022-12-16 02:47 UTC, edrickhoo commented on src/components/Book/Book.tsx
> +          : `Author: ${author}`}
Fixed

2022-12-16 02:47 UTC, edrickhoo commented on src/App.tsx
> +    } catch (err: any) {
Tried to change still get an Error

![image](https://user-images.githubusercontent.com/107743662/208010289-06032d9f-0082-4e12-94ad-002444ee1deb.png)

2022-12-16 05:09 UTC, merged